{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "daps-server.fullname" . }}
  labels:
    {{- include "daps-server.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | default "azurefile" }}
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}

{{- end }}
